"""Service layer: the supported API for reading and writing the issue graph.

Split by direction of data flow - `issue_service` mutates, `issue_query_service`
reads. Callers (the MCP tools, tests, or embedding code) import from here
rather than reaching into the submodules, so internals can move without
breaking them.
"""

from ..domain import (
    ACTIVE_STATUSES,
    ALL_DEPENDENCY_TYPES,
    ALL_ISSUE_TYPES,
    ALL_STATUSES,
    BLOCKING_DEPENDENCY_TYPES,
    DEFAULT_PRIORITY,
    DEP_BLOCKS,
    DEP_DUPLICATES,
    DEP_PARENT_CHILD,
    DEP_RELATED,
    DEP_SUPERSEDES,
    MAX_PRIORITY,
    MAX_TITLE_LENGTH,
    MIN_PRIORITY,
    STATUS_BLOCKED,
    STATUS_CLOSED,
    STATUS_DEFERRED,
    STATUS_IN_PROGRESS,
    STATUS_OPEN,
    TYPE_EPIC,
    TYPE_SUBTASK,
    TYPE_TASK,
    ValidationError,
)
from .issue_query_service import (
    find_cycles,
    get_blocked_issues,
    get_issue_details,
    get_issue_stats,
    get_issue_tree,
    get_ready_work,
    list_issues,
)
from .issue_service import (
    DependencyCycleError,
    IssueKwargs,
    IssueNotFoundError,
    add_comment,
    add_dependency,
    add_event,
    add_labels,
    claim_issue,
    close_issue,
    create_child_issue,
    create_epic_with_children,
    create_issue,
    delete_issue,
    remove_dependency,
    remove_labels,
    reopen_issue,
    set_labels,
    unassign_issue,
    update_issue_fields,
)

__all__ = [
    # Vocabulary
    "ACTIVE_STATUSES",
    "ALL_DEPENDENCY_TYPES",
    "ALL_ISSUE_TYPES",
    "ALL_STATUSES",
    "BLOCKING_DEPENDENCY_TYPES",
    "DEFAULT_PRIORITY",
    "MAX_PRIORITY",
    "MAX_TITLE_LENGTH",
    "MIN_PRIORITY",
    "STATUS_OPEN",
    "STATUS_IN_PROGRESS",
    "STATUS_BLOCKED",
    "STATUS_DEFERRED",
    "STATUS_CLOSED",
    "DEP_BLOCKS",
    "DEP_PARENT_CHILD",
    "DEP_RELATED",
    "DEP_DUPLICATES",
    "DEP_SUPERSEDES",
    "TYPE_TASK",
    "TYPE_SUBTASK",
    "TYPE_EPIC",
    # Errors
    "ValidationError",
    "IssueNotFoundError",
    "DependencyCycleError",
    # Types
    "IssueKwargs",
    # Writes
    "create_issue",
    "create_child_issue",
    "create_epic_with_children",
    "add_labels",
    "remove_labels",
    "set_labels",
    "add_dependency",
    "remove_dependency",
    "add_comment",
    "add_event",
    "update_issue_fields",
    "claim_issue",
    "unassign_issue",
    "close_issue",
    "reopen_issue",
    "delete_issue",
    # Reads
    "get_issue_details",
    "list_issues",
    "get_ready_work",
    "get_blocked_issues",
    "get_issue_tree",
    "get_issue_stats",
    "find_cycles",
]
