"""Initial migration CON MCP

Revision ID: 0c99887d9312
Revises:
Create Date: 2026-01-07 10:36:31.148759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c99887d9312"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "con_mcp_config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "con_mcp_issues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("acceptance_criteria", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("issue_type", sa.String(), nullable=False),
        sa.Column("assignee", sa.String(), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("length(title) <= 500", name="ck_con_mcp_issues_title_len"),
        sa.CheckConstraint(
            "priority >= 0 AND priority <= 4", name="ck_con_mcp_issues_priority_range"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_con_mcp_issues_assignee", "con_mcp_issues", ["assignee"], unique=False
    )
    op.create_index(
        "idx_con_mcp_issues_created_at", "con_mcp_issues", ["created_at"], unique=False
    )
    op.create_index(
        "idx_con_mcp_issues_priority", "con_mcp_issues", ["priority"], unique=False
    )
    op.create_index(
        "idx_con_mcp_issues_status", "con_mcp_issues", ["status"], unique=False
    )
    op.create_table(
        "con_mcp_child_counters",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("last_child", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["con_mcp_issues.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("parent_id"),
    )
    op.create_table(
        "con_mcp_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["con_mcp_issues.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_con_mcp_comments_created_at",
        "con_mcp_comments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_con_mcp_comments_issue", "con_mcp_comments", ["issue_id"], unique=False
    )
    op.create_table(
        "con_mcp_dependencies",
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_id"], ["con_mcp_issues.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["con_mcp_issues.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("issue_id", "depends_on_id"),
    )
    op.create_index(
        "idx_con_mcp_dependencies_depends_on",
        "con_mcp_dependencies",
        ["depends_on_id"],
        unique=False,
    )
    op.create_index(
        "idx_con_mcp_dependencies_depends_on_type",
        "con_mcp_dependencies",
        ["depends_on_id", "type"],
        unique=False,
    )
    op.create_index(
        "idx_con_mcp_dependencies_depends_on_type_issue",
        "con_mcp_dependencies",
        ["depends_on_id", "type", "issue_id"],
        unique=False,
    )
    op.create_index(
        "idx_con_mcp_dependencies_issue",
        "con_mcp_dependencies",
        ["issue_id"],
        unique=False,
    )
    op.create_table(
        "con_mcp_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["con_mcp_issues.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_con_mcp_events_created_at", "con_mcp_events", ["created_at"], unique=False
    )
    op.create_index(
        "idx_con_mcp_events_issue", "con_mcp_events", ["issue_id"], unique=False
    )
    op.create_table(
        "con_mcp_labels",
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["con_mcp_issues.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("issue_id", "label"),
    )
    op.create_index(
        "idx_con_mcp_labels_label", "con_mcp_labels", ["label"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_con_mcp_labels_label", table_name="con_mcp_labels")
    op.drop_table("con_mcp_labels")
    op.drop_index("idx_con_mcp_events_issue", table_name="con_mcp_events")
    op.drop_index("idx_con_mcp_events_created_at", table_name="con_mcp_events")
    op.drop_table("con_mcp_events")
    op.drop_index("idx_con_mcp_dependencies_issue", table_name="con_mcp_dependencies")
    op.drop_index(
        "idx_con_mcp_dependencies_depends_on_type_issue",
        table_name="con_mcp_dependencies",
    )
    op.drop_index(
        "idx_con_mcp_dependencies_depends_on_type", table_name="con_mcp_dependencies"
    )
    op.drop_index(
        "idx_con_mcp_dependencies_depends_on", table_name="con_mcp_dependencies"
    )
    op.drop_table("con_mcp_dependencies")
    op.drop_index("idx_con_mcp_comments_issue", table_name="con_mcp_comments")
    op.drop_index("idx_con_mcp_comments_created_at", table_name="con_mcp_comments")
    op.drop_table("con_mcp_comments")
    op.drop_table("con_mcp_child_counters")
    op.drop_index("idx_con_mcp_issues_status", table_name="con_mcp_issues")
    op.drop_index("idx_con_mcp_issues_priority", table_name="con_mcp_issues")
    op.drop_index("idx_con_mcp_issues_created_at", table_name="con_mcp_issues")
    op.drop_index("idx_con_mcp_issues_assignee", table_name="con_mcp_issues")
    op.drop_table("con_mcp_issues")
    op.drop_table("con_mcp_config")
    # ### end Alembic commands ###
